name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: surge ./ https://tu-nombre-de-sitio.surge.sh
